module.exports = {
  "status": "wip",
  "notes": "Example Page - https://www.usa.gov/features",
  "context": {
    "tid": "11003",
    "name": "Features",
    "description": null,
    "format": "filtered_html",
    "weight": "1",
    "changed": "1520483873",
    "uuid": "c458c7fd-667e-49e2-9cff-5b4365c937ac",
    "vocabulary_machine_name": "site_strucutre_taxonomy",
    "path": "1",
    "type": "taxonomy_term",
    "deleted": null,
    "parent_uuid": "07885dba-ccbe-40a7-9e1f-6781bad99b58",
    "parent": "11041",
    "children": [],
    "govdelivery_id": null,
    "page_intro": "You're invited to read and use our bilingual articles covering trusted, timely, and valuable government information.",
    "head_html": null,
    "end_html": "<script type=\"text\/javascript\">\r\njQuery(document).ready( function () {\r\n$('#pagesurvey-hdr').hide();\r\n$('#pagesurvey-trgt').hide();\r\n$('#pagesurvey-ombnum').hide();\r\n});\r\n<\/script>",
    "generate_page": "no",
    "also_include_on_nav_page": [],
    "asset_topic_taxonomy": [],
    "page_title": "Features",
    "usefulness_survey": "0",
    "browser_title": "Features",
    "friendly_url": "\/features",
    "usa_gov_toggle_url": null,
    "gobiernousa_gov_toggle_url": "\/novedades",
    "type_of_page_to_generate": "generic-content-page",
    "asset_inherit_carousel": "0",
    "asset_inherit_content": "0",
    "asset_inherit_sidebar": "0",
    "asset_inherit_bottom": "0",
    "asset_order_carousel": [],
    "asset_order_content": [
      {
          "target_id": "213862",
          "uuid": "e4f9a27b-550d-4964-bffd-8f7d128c61c3",
          "type": "node",
          "bundle": "text_content_type"
      },
      {
          "target_id": "213383",
          "uuid": "44c33ecc-f0e4-4a70-a2f3-10f9facbe044",
          "type": "node",
          "bundle": "text_content_type"
      },
      {
          "target_id": "212751",
          "uuid": "ecb22e1c-0cfe-4e58-a9fa-29890e0a1d67",
          "type": "node",
          "bundle": "text_content_type"
      },
      {
          "target_id": "213804",
          "uuid": "75c81385-1bb0-4912-9d23-7f12deb13bc4",
          "type": "node",
          "bundle": "text_content_type"
      },
      {
          "target_id": "213823",
          "uuid": "ee77187e-4996-46f8-9c83-2dc5418f04d1",
          "type": "node",
          "bundle": "text_content_type"
      },
      {
          "target_id": "213753",
          "uuid": "fe91f32a-c84b-4211-a339-3e3253c713b9",
          "type": "node",
          "bundle": "text_content_type"
      },
      {
          "target_id": "211842",
          "uuid": "689a061b-4ca3-4621-ab5c-944e74b1fae1",
          "type": "node",
          "bundle": "text_content_type"
      }
    ],
    "asset_order_sidebar": [],
    "asset_order_bottom": [],
    "asset_inherit_menu": "0",
    "asset_order_menu": null,
    "generate_menu": "yes",
    "css_class": null,
    "usa_gov_50_state_category": null,
    "directory_record_access_me": null,
    "directory_record_url": null,
    "home_alert_asset": null,
    "show_social_media_icon": null,
    "term_owner": null,
    "help_desk": null,
    "usa_gov_50_state_prefix": null,
    "home_howdoi_assets": [],
    "home_whats_new_asset": [],
    "government_branch": null,
    "real_meta_description": "You're invited to read and use our bilingual articles covering trusted, timely, and valuable government information.",
    "description_meta": "You're invited to read and use our bilingual articles covering trusted, timely, and valuable government information.",
    "for_use_by": "USA.gov",
    "pageType": "GenericContentPage",
    "menu": [],
    "child_pages": [],
    "parent_menu": [
        {
            "uuid": "c458c7fd-667e-49e2-9cff-5b4365c937ac",
            "name": "Features",
            "friendly_url": "\/features",
            "css_class": null,
            "description_meta": "You're invited to read and use our bilingual articles covering trusted, timely, and valuable government information.",
            "sub": []
        },
        {
            "uuid": "b156b066-6594-45cd-9147-0e1de31c0399",
            "name": "Partner with Us",
            "friendly_url": "\/partner-with-us",
            "css_class": null,
            "description_meta": "Learn how the media, community-based organizations, and U.S. government agencies can partner with USAGov.",
            "sub": []
        }
    ],
    "entities": {
      "e4f9a27b-550d-4964-bffd-8f7d128c61c3": {
          "title": "This Valentine\u2019s Day Help Someone Experiencing Abuse",
          "log": "Edited by andrea.castelluccio@gsa.gov.",
          "status": "1",
          "sticky": null,
          "vuuid": "e56f8cdd-98df-4937-8cc4-b69ddfc5d8d5",
          "nid": "213862",
          "type": "text_content_type",
          "language": "Spanish",
          "created": "1517928103",
          "changed": "1517939191",
          "tnid": null,
          "translate": null,
          "uuid": "e4f9a27b-550d-4964-bffd-8f7d128c61c3",
          "body": "<p>The greeting card aisle crams with shoppers, struggling to find the right sentiment. Buyers line up at the register with heart-shaped boxes of chocolate and keep florists busy juggling orders for beautiful bouquets. It&rsquo;s all part of the excitement and romance of Valentine&rsquo;s Day. But for someone who&rsquo;s recovering from sexual assault or living with domestic violence, all of the cards and roses in the world can&rsquo;t make up for the pain.<\/p><p>If you want to support a friend in this difficult situation, or if you need support yourself,&nbsp;<a href=\"https:\/\/www.usa.gov\/explore\/\">USAGov<\/a>&nbsp;has gathered these resources to help:<\/p><h3>When your friend needs you<\/h3><p>&ldquo;You really don&rsquo;t know unless you&rsquo;ve been there.&rdquo; From the outside, it can be hard to understand why people hesitate to report a sexual assault or&nbsp;<a href=\"http:\/\/www.womenshealth.gov\/violence-against-women\/types-of-violence\/domestic-intimate-partner-violence.html#g\">stay in abusive relationships<\/a>. But there are a lot of reasons: fear that no one would believe them--especially if the attacker is respected in the community; concern for their own or their children&rsquo;s safety; financial instability; or feeling--because of the abuser&rsquo;s mind games--that they deserve the abuse. Learn how to help your friend move toward safety and healing with these&nbsp;<a href=\"http:\/\/womenshealth.gov\/violence-against-women\/get-help-for-violence\/how-to-help-a-friend-who-is-being-abused.html\">suggestions from WomensHealth.gov<\/a>.<\/p><h3>When you&rsquo;re a bystander<\/h3><p>If you&rsquo;re a college student, you might have heard about sexual assaults on your campus. Some of those assaults may have been prevented if bystanders had spoken up. The&nbsp;<a href=\"http:\/\/www.itsonus.org\/\">It&rsquo;s On Us<\/a>&nbsp;campaign works to prevent sexual assault by changing the college culture. Get&nbsp;<a href=\"http:\/\/www.itsonus.org\/tools\/\">tips and tools<\/a>&nbsp;to teach you to trust that knot in your stomach when something doesn&rsquo;t seem right and&nbsp;<a href=\"https:\/\/www.womenshealth.gov\/violence-against-women\/help-end-violence-against-women\/index.html\">take action<\/a>&nbsp;to help end violence against women.<\/p><h3>When you&rsquo;re the one who&rsquo;s hurting<\/h3><p>Living through&nbsp;<a href=\"https:\/\/www.girlshealth.gov\/safety\/saferelationships\/daterape.html\">rape<\/a>&nbsp;or domestic violence can be isolating and shocking, and it can leave you wrapped in shame and hopelessness. Your partner may try to convince you that you&rsquo;re not really being abused, or that it&rsquo;s your fault. This list of&nbsp;<a href=\"http:\/\/womenshealth.gov\/violence-against-women\/am-i-being-abused\/index.html\">signs of abuse<\/a>&nbsp;can help you evaluate what you&rsquo;re experiencing.<\/p><p>Even if you&rsquo;re not ready to make a report to the police, you can still begin&nbsp;<a href=\"http:\/\/www.womenshealth.gov\/violence-against-women\/get-help-for-violence\/safety-planning-for-abusive-situations.html\">creating a safety plan<\/a>&nbsp;to leave a dangerous situation. And you can reach out for non-judgmental support anonymously, day or night, from the&nbsp;<a href=\"http:\/\/www.thehotline.org\/help\/\">National Domestic Violence Hotline<\/a>&nbsp;at&nbsp;<a href=\"tel:18007997233\">1-800-799-7233<\/a>. You can also contact the&nbsp;<a href=\"https:\/\/rainn.org\/get-help\/national-sexual-assault-hotline\">National Sexual Assault Hotline<\/a>&nbsp;at&nbsp;<a href=\"tel:18006564673\">1-800-656-HOPE<\/a>&nbsp;(4673). If possible, contact them from a phone or computer account that your abuser can&rsquo;t access so they won&rsquo;t be able to trace your call records or browsing history.<\/p><p>These organizations are ready to refer you to local help for counseling; treatment for stress, depression, or trauma; and housing and child care programs. With them, and with supportive friends and family, you won&rsquo;t have to be alone during this difficult time.<\/p><p>The government is filled with programs and services that can help make life a little easier and safer for you and your family. Let USAGov be your guide at&nbsp;<a href=\"https:\/\/www.usa.gov\/explore\/\">USA.gov\/explore<\/a>.<\/p>",
          "name": "andrea.castelluccio@gsa.gov",
          "deleted": null,
          "comments": null,
          "description": "If you want to support a friend in this difficult situation, or if you need support yourself, USAGov has gathered these resources to help.",
          "notify_marketing_team": "No",
          "contact_center_info": null,
          "for_use_by_text": [
              "USA.gov",
              "Feature"
          ],
          "schedule_publish": null,
          "archive_date": null,
          "date_last_reviewed": null,
          "content_tags": null,
          "asset_topic_taxonomy": [
              {
                  "tid": "11098",
                  "uuid": "916901b3-0032-47cf-b785-d1864c0562fa",
                  "type": "taxonomy_term",
                  "bundle": "asset_topic_taxonomy"
              },
              {
                  "tid": "11726",
                  "uuid": "81b5336e-8c53-45e5-8d39-67da44802cce",
                  "type": "taxonomy_term",
                  "bundle": "asset_topic_taxonomy"
              }
          ],
          "related_multimedia_two": {
              "target_id": "212507",
              "uuid": "64445c0c-55a6-4bd8-a724-ad325374305e",
              "type": "node",
              "bundle": "multimedia_content_type"
          },
          "priority": "normal",
          "workflow_state_search": null,
          "blog_owner": null,
          "blog_pub_date": "1517928109",
          "usa_feature_toggle_url": null,
          "gob_feature_toggle_url": "\/novedades\/en-el-dia-de-san-valentin-digale-no-al-abuso",
          "for_use_by": [
              "USA.gov",
              "Feature"
          ],
          "pageType": null
      },
      "64445c0c-55a6-4bd8-a724-ad325374305e": {
          "title": "Bouquets and Roses English",
          "log": "Edited by julia.sultan@gsa.gov.",
          "status": "1",
          "sticky": null,
          "vuuid": "2ab6ea7b-d4e9-4c0c-96ac-26b3a6f552ba",
          "nid": "212507",
          "type": "multimedia_content_type",
          "language": "English",
          "created": "1455028955",
          "changed": "1517952256",
          "tnid": null,
          "translate": null,
          "uuid": "64445c0c-55a6-4bd8-a724-ad325374305e",
          "name": "edgardo.morales@gsa.gov",
          "deleted": null,
          "alt_text": "A flower on the ground. ",
          "comments": null,
          "description": "Image for feature. ",
          "embed_code": null,
          "for_use_by": "USA.gov",
          "media_type": "Image",
          "notify_marketing_team": "No",
          "transcript": null,
          "schedule_publish": null,
          "archive_date": null,
          "date_last_reviewed": null,
          "content_tags": null,
          "asset_topic_taxonomy": [],
          "url": null,
          "high_res_version": null,
          "widget_code": null,
          "priority": "normal",
          "info_for_contact_center": null,
          "workflow_state_search": null,
          "file_media": {
              "fid": "d8d02a49-90b2-40a8-a807-796afc308fd2",
              "uid": "afc1e1c6-348b-433b-b81b-1ee5a882c4dd",
              "filename": "Bouquets and Roses.jpg",
              "uri": "\/\/app_usa_prod_eqffnyamdzrb.s3.amazonaws.com\/Bouquets and Roses_0.jpg",
              "filemime": "image\/jpeg",
              "filesize": "46372",
              "status": "1",
              "timestamp": "1455028934",
              "type": "image",
              "uuid": "d8d02a49-90b2-40a8-a807-796afc308fd2",
              "field_file_image_alt_text": [],
              "field_file_image_title_text": [],
              "_drafty_revision_requested": "FIELD_LOAD_CURRENT",
              "rdf_mapping": [],
              "metadata": {
                  "height": 558,
                  "width": 600
              },
              "height": "558",
              "width": "600",
              "alt": null,
              "title": null
          },
          "pageType": null
      },
      "44c33ecc-f0e4-4a70-a2f3-10f9facbe044": {
          "title": "Bouquets and Bruises: This Valentine\u2019s Day, Help Someone Experiencing Abuse",
          "log": "Edited by andrea.castelluccio@gsa.gov.",
          "status": "1",
          "sticky": null,
          "vuuid": "7d42beea-b8bf-4260-9720-374668b93f82",
          "nid": "213383",
          "type": "text_content_type",
          "language": "English",
          "created": "1486673053",
          "changed": "1517931699",
          "tnid": null,
          "translate": null,
          "uuid": "44c33ecc-f0e4-4a70-a2f3-10f9facbe044",
          "body": "<p>The greeting card aisle crams with shoppers, struggling to find the right sentiment. Buyers line up at the register with heart-shaped boxes of chocolate and keep florists busy juggling orders for beautiful bouquets. It&rsquo;s all part of the excitement and romance of Valentine&rsquo;s Day. But for someone who&rsquo;s recovering from sexual assault or living with domestic violence, all of the cards and roses in the world can&rsquo;t make up for the pain.<\/p><p>If you want to support a friend in this difficult situation, or if you need support yourself, <a href=\"https:\/\/www.usa.gov\/explore\/\">USAGov<\/a> has gathered these resources to help:<\/p><h3>When your friend needs you<\/h3><p>&ldquo;You really don&rsquo;t know unless you&rsquo;ve been there.&rdquo; From the outside, it can be hard to understand why people hesitate to report a sexual assault or <a href=\"http:\/\/www.womenshealth.gov\/violence-against-women\/types-of-violence\/domestic-intimate-partner-violence.html#g\">stay in abusive relationships<\/a>. But there are a lot of reasons: fear that no one would believe them--especially if the attacker is respected in the community; concern for their own or their children&rsquo;s safety; financial instability; or feeling--because of the abuser&rsquo;s mind games--that they deserve the abuse. Learn how to help your friend move toward safety and healing with these <a href=\"http:\/\/womenshealth.gov\/violence-against-women\/get-help-for-violence\/how-to-help-a-friend-who-is-being-abused.html\">suggestions from WomensHealth.gov<\/a>.<\/p><h3>When you&rsquo;re a bystander<\/h3><p>If you&rsquo;re a college student, you might have heard about sexual assaults on your campus. Some of those assaults may have been prevented if bystanders had spoken up. The <a href=\"http:\/\/www.itsonus.org\/\">It&rsquo;s On Us<\/a> campaign works to prevent sexual assault by changing the college culture. Get <a href=\"http:\/\/www.itsonus.org\/tools\/\">tips and tools<\/a> to teach you to trust that knot in your stomach when something doesn&rsquo;t seem right and <a href=\"https:\/\/www.womenshealth.gov\/violence-against-women\/help-end-violence-against-women\/index.html\">take action<\/a> to help end violence against women.<\/p><h3>When you&rsquo;re the one who&rsquo;s hurting<\/h3><p>Living through <a href=\"https:\/\/www.girlshealth.gov\/safety\/saferelationships\/daterape.html\">rape<\/a> or domestic violence can be isolating and shocking, and it can leave you wrapped in shame and hopelessness. Your partner may try to convince you that you&rsquo;re not really being abused, or that it&rsquo;s your fault. This list of <a href=\"http:\/\/womenshealth.gov\/violence-against-women\/am-i-being-abused\/index.html\">signs of abuse<\/a> can help you evaluate what you&rsquo;re experiencing.<\/p><p>Even if you&rsquo;re not ready to make a report to the police, you can still begin <a href=\"http:\/\/www.womenshealth.gov\/violence-against-women\/get-help-for-violence\/safety-planning-for-abusive-situations.html\">creating a safety plan<\/a> to leave a dangerous situation. And you can reach out for non-judgmental support anonymously, day or night, from the <a href=\"http:\/\/www.thehotline.org\/help\/\">National Domestic Violence Hotline<\/a> at <a href=\"tel:18007997233\">1-800-799-7233<\/a>. You can also contact the <a href=\"https:\/\/rainn.org\/get-help\/national-sexual-assault-hotline\">National Sexual Assault Hotline<\/a> at <a href=\"tel:18006564673\">1-800-656-HOPE<\/a> (4673). If possible, contact them from a phone or computer account that your abuser can&rsquo;t access so they won&rsquo;t be able to trace your call records or browsing history.<\/p><p>These organizations are ready to refer you to local help for counseling; treatment for stress, depression, or trauma; and housing and child care programs. With them, and with supportive friends and family, you won&rsquo;t have to be alone during this difficult time.<\/p><p>The government is filled with programs and services that can help make life a little easier and safer for you and your family. Let USAGov be your guide at <a href=\"https:\/\/www.usa.gov\/explore\/\">USA.gov\/explore<\/a>.<\/p><p><a href=\"https:\/\/gobierno.usa.gov\/novedades\/rosas-y-espinas-en-este-dia-de-san-valentin,-digale-no-al-abuso\">En espa\u00f1ol<\/a>.<\/p>",
          "name": "andrea.castelluccio@gsa.gov",
          "deleted": null,
          "comments": null,
          "description": "If you want to support a friend in this difficult situation, or if you need support yourself, USAGov has gathered these resources to help.",
          "notify_marketing_team": "No",
          "contact_center_info": null,
          "for_use_by_text": [
              "USA.gov",
              "Feature"
          ],
          "schedule_publish": null,
          "archive_date": null,
          "date_last_reviewed": null,
          "content_tags": null,
          "asset_topic_taxonomy": [
              {
                  "tid": "11098",
                  "uuid": "916901b3-0032-47cf-b785-d1864c0562fa",
                  "type": "taxonomy_term",
                  "bundle": "asset_topic_taxonomy"
              }
          ],
          "related_multimedia_two": {
              "target_id": "212507",
              "uuid": "64445c0c-55a6-4bd8-a724-ad325374305e",
              "type": "node",
              "bundle": "multimedia_content_type"
          },
          "priority": "normal",
          "workflow_state_search": "draft",
          "blog_owner": null,
          "blog_pub_date": "1486673056",
          "usa_feature_toggle_url": "\/features\/this-valentines-day-help-someone-experiencing-abuse",
          "gob_feature_toggle_url": null,
          "for_use_by": [
              "USA.gov",
              "Feature"
          ],
          "pageType": null
      },
      "64445c0c-55a6-4bd8-a724-ad325374305e": {
          "title": "Bouquets and Roses English",
          "log": "Edited by julia.sultan@gsa.gov.",
          "status": "1",
          "sticky": null,
          "vuuid": "2ab6ea7b-d4e9-4c0c-96ac-26b3a6f552ba",
          "nid": "212507",
          "type": "multimedia_content_type",
          "language": "English",
          "created": "1455028955",
          "changed": "1517952256",
          "tnid": null,
          "translate": null,
          "uuid": "64445c0c-55a6-4bd8-a724-ad325374305e",
          "name": "edgardo.morales@gsa.gov",
          "deleted": null,
          "alt_text": "A flower on the ground. ",
          "comments": null,
          "description": "Image for feature. ",
          "embed_code": null,
          "for_use_by": "USA.gov",
          "media_type": "Image",
          "notify_marketing_team": "No",
          "transcript": null,
          "schedule_publish": null,
          "archive_date": null,
          "date_last_reviewed": null,
          "content_tags": null,
          "asset_topic_taxonomy": [],
          "url": null,
          "high_res_version": null,
          "widget_code": null,
          "priority": "normal",
          "info_for_contact_center": null,
          "workflow_state_search": null,
          "file_media": {
              "fid": "d8d02a49-90b2-40a8-a807-796afc308fd2",
              "uid": "afc1e1c6-348b-433b-b81b-1ee5a882c4dd",
              "filename": "Bouquets and Roses.jpg",
              "uri": "\/\/app_usa_prod_eqffnyamdzrb.s3.amazonaws.com\/Bouquets and Roses_0.jpg",
              "filemime": "image\/jpeg",
              "filesize": "46372",
              "status": "1",
              "timestamp": "1455028934",
              "type": "image",
              "uuid": "d8d02a49-90b2-40a8-a807-796afc308fd2",
              "field_file_image_alt_text": [],
              "field_file_image_title_text": [],
              "_drafty_revision_requested": "FIELD_LOAD_CURRENT",
              "rdf_mapping": [],
              "metadata": {
                  "height": 558,
                  "width": 600
              },
              "height": "558",
              "width": "600",
              "alt": null,
              "title": null
          },
          "pageType": null
      },
      "ecb22e1c-0cfe-4e58-a9fa-29890e0a1d67": {
          "title": "USAGov\u2019s Five Tips to Get Great Deals from Government Auctions and Sales",
          "log": "Edited by julia.sultan@gsa.gov.",
          "status": "1",
          "sticky": null,
          "vuuid": "3e3c68da-2546-4fa0-b6b7-2c24f1eaadb9",
          "nid": "212751",
          "type": "text_content_type",
          "language": "English",
          "created": "1462822706",
          "changed": "1517865920",
          "tnid": null,
          "translate": null,
          "uuid": "ecb22e1c-0cfe-4e58-a9fa-29890e0a1d67",
          "body": "<p>You may have heard that you can buy &ldquo;stuff&rdquo; from the government. But how does it work? Can you really get good deals? With these tips from <a href=\"https:\/\/www.usa.gov\/explore\/\">USAGov<\/a>, you can learn how to be a smart shopper at <a href=\"https:\/\/www.usa.gov\/auctions-and-sales\">government auctions and sales<\/a> and discover the surprising variety of things you can buy:<\/p><p><strong>Who sells government property?<\/strong><\/p><p>Many <a href=\"https:\/\/www.usa.gov\/auctions-and-sales#item-36607\">federal agencies,<\/a> <a href=\"https:\/\/www.usa.gov\/state-surplus-sales\">states<\/a>, and even some local governments sell property that&rsquo;s surplus or has been seized by law enforcement. For a variety of property types, try:<\/p><ul><li><a href=\"http:\/\/gsaauctions.gov\/gsaauctions\/gsaauctions\/\">GSA Auctions<\/a>, the government&rsquo;s national electronic bidding site for buying federal assets, from common household items to specialized equipment and vehicles<\/li><li><a href=\"http:\/\/www.govsales.gov\/\">GovSales.gov<\/a>, listing all the government&rsquo;s property for sale, including real estate<\/li><\/ul><p><strong>What &ldquo;stuff&rdquo; can you buy?<\/strong><\/p><p>You can buy everyday items&mdash;chairs, desks, furniture, computers, and electronic equipment&mdash;that can go in your home or office. You can also buy hand tools, watches, and jewelry, as well as vehicles, including cars, trucks, boats, and even airplanes!<\/p><p>If you&rsquo;re interested in <a href=\"http:\/\/homesales.gov\/homesales\/mainAction.do\">buying a house<\/a>, the government offers foreclosed single family homes. But make sure you work with a real estate agent, broker, or servicing representative to make an offer or bid. You can also find <a href=\"http:\/\/fasrp.sc.egov.usda.gov\/fasrp\/mainAction.do?pageAction=\">commercial real estate and land for sale<\/a>. This surplus property includes office buildings, warehouses, commercial facilities, and former post offices. If you still haven&rsquo;t found something, you might consider buying <a href=\"https:\/\/www.treasury.gov\/auctions\/irs\/\">seized properties<\/a> from the IRS. Remember: Even though you can find considerable savings on government-owned property, everything sells at fair-market value.<\/p><p><strong>How can you buy government property?<\/strong><\/p><p>While there are many ways to <a href=\"http:\/\/www.gsa.gov\/portal\/content\/100756\">buy surplus personal property<\/a> and <a href=\"http:\/\/fasrp.sc.egov.usda.gov\/fasrp\/HowToBuy.jsp\">real estate<\/a> from the government, these are three popular sales methods:<\/p><ul><li>Live auctions - You can find many types of items like cars and trucks for sale at one location. Either before or on the day of the auction, you&rsquo;ll receive descriptions, instructions on how to bid, and the chance to inspect the merchandise. Sometimes you can find special items highlighted in print and online media.<\/li><li>Online auctions - For surplus personal property, <a href=\"http:\/\/gsaauctions.gov\/gsaauctions\/gsaauctions\/\">register on GSA Auctions<\/a>. You can search for items by various categories and bid electronically. Keep in mind that once you place a successful bid on an item, you&rsquo;ll have to pay for it within two business days and pick it up within 10 business days. For other government property for sale, including real estate, start at <a href=\"http:\/\/www.govsales.gov\/\">GovSales.gov<\/a>. Once you&rsquo;ve found what you&rsquo;re looking for, follow the bidding instructions.<\/li><li>Fixed-price sales - In this type of sale, all items have non-negotiable price tags. You can come in person to inspect, purchase, and take the non-returnable merchandise with you.<\/li><\/ul><p><strong>When is the best time to buy?<\/strong><\/p><p>The government hosts many types of <a href=\"http:\/\/gsaauctions.gov\/html\/surplussales\/index.html\">surplus personal property<\/a> and real estate sales&mdash;both in person and online&mdash;throughout the year. For sales online, there&rsquo;s no specific time frame, though sales typically last a week. There&rsquo;s a constantly cycling inventory, so you&rsquo;ll want to check the listings daily to find the best deals.<\/p><p><strong>Why buy from the government?<\/strong><\/p><p>You can make your money go farther on a wide variety of individual items. And that goes for bulk items, such as laptops, cell phones, and other electronic equipment, too. If you&rsquo;re in the market for a car, government vehicles are exceptionally well maintained and often come with detailed paperwork, as opposed to buying through a private dealer, who might not know the vehicle&rsquo;s maintenance history. You can also take heart in knowing that all proceeds from government sales go back to the original holding or selling agency, to the Land and Water Conservation Fund, or are deposited in the U.S. Treasury&rsquo;s general fund. And while there are no giveaways&mdash;yachts don&rsquo;t come cheap&mdash;the discounted prices give you another reason to try out a government sale.<\/p><p>Learn more about <a href=\"https:\/\/www.usa.gov\/buy-from-government\">buying from the government<\/a> on USA.gov, your online guide to government information and services. Whether you&rsquo;re looking for surplus sales, collectibles, or other government-owned property available through purchase or auction, you&rsquo;ll find the information and services you need.<\/p><p><a href=\"http:\/\/gobierno.usa.gov\/novedades\/cinco-tips-para-obtener-buenas-ofertas-en-subastas-y-ventas-del-gobierno\">En espa\u00f1ol<\/a>.<\/p>",
          "name": "edgardo.morales@gsa.gov",
          "deleted": null,
          "comments": null,
          "description": "You may have heard that you can buy \u201cstuff\u201d from the government. But how does it work? Can you really get good deals?",
          "notify_marketing_team": "No",
          "contact_center_info": null,
          "for_use_by_text": [
              "USA.gov",
              "Feature"
          ],
          "schedule_publish": null,
          "archive_date": null,
          "date_last_reviewed": null,
          "content_tags": {
              "tid": "261",
              "uuid": "872f4f04-cb8f-4d0c-aa65-9ed93e8bb923",
              "type": "taxonomy_term",
              "bundle": "agency_tags"
          },
          "asset_topic_taxonomy": [
              {
                  "tid": "11098",
                  "uuid": "916901b3-0032-47cf-b785-d1864c0562fa",
                  "type": "taxonomy_term",
                  "bundle": "asset_topic_taxonomy"
              },
              {
                  "tid": "11245",
                  "uuid": "895b39e3-8f88-42b8-955a-24c2ca916211",
                  "type": "taxonomy_term",
                  "bundle": "asset_topic_taxonomy"
              }
          ],
          "related_multimedia_two": {
              "target_id": "212750",
              "uuid": "04d83757-58e2-4ce8-8fa2-c4e029ee1c4f",
              "type": "node",
              "bundle": "multimedia_content_type"
          },
          "priority": "normal",
          "workflow_state_search": "draft",
          "blog_owner": null,
          "blog_pub_date": "1462822711",
          "usa_feature_toggle_url": null,
          "gob_feature_toggle_url": null,
          "for_use_by": [
              "USA.gov",
              "Feature"
          ],
          "pageType": null
      },
      "04d83757-58e2-4ce8-8fa2-c4e029ee1c4f": {
          "title": "Auctions Image Eng",
          "log": "Edited by julia.sultan@gsa.gov.",
          "status": "1",
          "sticky": null,
          "vuuid": "1cf99136-7251-4167-979e-79a09e7cda98",
          "nid": "212750",
          "type": "multimedia_content_type",
          "language": "English",
          "created": "1462821446",
          "changed": "1517857354",
          "tnid": null,
          "translate": null,
          "uuid": "04d83757-58e2-4ce8-8fa2-c4e029ee1c4f",
          "name": "edgardo.morales@gsa.gov",
          "deleted": null,
          "alt_text": "person with auction dollar sign in the hands",
          "comments": null,
          "description": "Image for feature. ",
          "embed_code": null,
          "for_use_by": "USA.gov",
          "media_type": "Image",
          "notify_marketing_team": "No",
          "transcript": null,
          "schedule_publish": null,
          "archive_date": null,
          "date_last_reviewed": null,
          "content_tags": null,
          "asset_topic_taxonomy": [],
          "url": null,
          "high_res_version": null,
          "widget_code": null,
          "priority": "normal",
          "info_for_contact_center": null,
          "workflow_state_search": null,
          "file_media": {
              "fid": "a8b8bef2-1c8d-4a76-b1da-d9bbbc768840",
              "uid": "afc1e1c6-348b-433b-b81b-1ee5a882c4dd",
              "filename": "Auction eng.jpg",
              "uri": "\/\/app_usa_prod_eqffnyamdzrb.s3.amazonaws.com\/Auction eng.jpg",
              "filemime": "image\/jpeg",
              "filesize": "36735",
              "status": "1",
              "timestamp": "1462821437",
              "type": "image",
              "uuid": "a8b8bef2-1c8d-4a76-b1da-d9bbbc768840",
              "field_file_image_alt_text": [],
              "field_file_image_title_text": [],
              "_drafty_revision_requested": "FIELD_LOAD_CURRENT",
              "rdf_mapping": [],
              "metadata": {
                  "height": 582,
                  "width": 600
              },
              "height": "582",
              "width": "600",
              "alt": null,
              "title": null
          },
          "pageType": null
      },
      "75c81385-1bb0-4912-9d23-7f12deb13bc4": {
          "title": "USAGov\u2019s Apps to Download in 2018",
          "log": "Edited by julia.sultan@gsa.gov.",
          "status": "1",
          "sticky": null,
          "vuuid": "76329908-3f80-43d0-87f1-6c2146224104",
          "nid": "213804",
          "type": "text_content_type",
          "language": "English",
          "created": "1513966020",
          "changed": "1517864484",
          "tnid": null,
          "translate": null,
          "uuid": "75c81385-1bb0-4912-9d23-7f12deb13bc4",
          "body": "<p>Ordering food, shopping, reviews and buying movie tickets, there&rsquo;s an app for everything. Did you know the government has apps available that make some tasks easier to handle? Others provide easier ways to contact or get information about certain programs.<\/p><p>Check out&nbsp;<a href=\"https:\/\/www.usa.gov\/explore\/\">USAGov<\/a>&rsquo;s apps to download in 2018:<\/p><h3>For children:<\/h3><ul><li><strong>NASA<\/strong> - An app for space enthusiasts. This app is home to all things NASA, including images, videos on-demand, mission information, ISS sighting opportunities, satellite tracking, and more. (<a href=\"https:\/\/itunes.apple.com\/app\/nasa-app\/id334325516?mt=8\">iOS<\/a>, <a href=\"https:\/\/play.google.com\/store\/apps\/details?id=gov.nasa\">Android<\/a>)<\/li><li><strong>Aesop for Children<\/strong> - This interactive book app is designed for readers of every age. The app contains more than 140 classic fables which remain popular for moral education of children. (<a href=\"https:\/\/play.google.com\/store\/apps\/details?id=gov.loc.osi.aesops\">Android<\/a>, <a href=\"http:\/\/itunes.apple.com\/us\/app\/aesop-for-children\/id538815234?mt=8\">iOS<\/a>)<\/li><\/ul><h3>For families:<\/h3><ul><li><strong>HUD Resource Locator<\/strong> - This is an easy to use app that helps users discover commonly requested federal housing resources within their community. Get information on many housing HUD programs, directly contact specific resource providers, and more. (<a href=\"https:\/\/itunes.apple.com\/us\/app\/hud-resource-locator\/id1018440488?mt=8\">iOS<\/a>, <a href=\"https:\/\/play.google.com\/store\/apps\/details?id=resources.hud.gov.resourcelocator_android&amp;hl=en\">Android<\/a>)<\/li><li><strong>USPS<\/strong> - Access tools on the go with the USPS Mobile&reg; app. Calculate shipping prices, find a Post Office&trade;, look up a ZIP Code&trade;, schedule a next-day pickup, request USPS to hold your mail, and more. (<a href=\"http:\/\/itunes.apple.com\/us\/app\/usps-mobile\/id339597578?mt=8\">iOS<\/a>, <a href=\"https:\/\/play.google.com\/store\/apps\/details?id=com.usps\">Android<\/a>)<\/li><li><strong>Safer Ride&nbsp;<\/strong>- the simplest possible way to get home safe and only has three self-explanatory buttons on the Home screen. (<a href=\"https:\/\/itunes.apple.com\/us\/app\/saferride\/id950774008?mt=8\">IOS<\/a>, <a href=\"https:\/\/play.google.com\/store\/apps\/details?id=com.nhtsa.SaferRide\">Android<\/a>)<\/li><\/ul><h3>For emergencies:<\/h3><ul><li><p><strong>FEMA app<\/strong> - This app is your one-stop-shop with tools and tips to keep you safe before, during, and after disasters. Get tips on what to do before, during, and after for more 20 types of disasters. Locate shelters and find out where to contact FEMA at disaster recovery centers. (<a href=\"http:\/\/itunes.apple.com\/us\/app\/fema\/id474807486?\">iOS<\/a>, <a href=\"https:\/\/play.google.com\/store\/apps\/details?id=gov.fema.mobile.android\">Android<\/a>)<\/p><\/li><\/ul><h3>For travelers:<\/h3><ul><li><p><strong>MyTSA<\/strong> - The MyTSA app provides airline passengers with 24\/7 access to the most frequently requested airport security information. Save time and money with helpful tips for preparing for security. &nbsp;(<a href=\"http:\/\/itunes.apple.com\/us\/app\/my-tsa\/id380200364?mt\">iOS<\/a> only)<\/p><\/li><li><p><strong>Smart Traveler<\/strong>- The official State Department app for U.S. travelers invites you to see the world with easy access to frequently updated official country information, travel alerts, travel warnings, maps, U.S. embassy locations, and more. (<a href=\"http:\/\/itunes.apple.com\/us\/app\/smart-traveler\/id442693988?mt=8\">iOS<\/a>, <a href=\"https:\/\/play.google.com\/store\/apps\/details?id=gov.state.apps.smarttraveler&amp;hl=en\">Android<\/a>)<\/p><\/li><\/ul>",
          "name": "andrea.castelluccio@gsa.gov",
          "deleted": null,
          "comments": null,
          "description": "Ordering food, shopping, reviews and buying movie tickets, there\u2019s an app for everything. Download these in 2018. ",
          "notify_marketing_team": "No",
          "contact_center_info": null,
          "for_use_by_text": [
              "USA.gov",
              "Feature"
          ],
          "schedule_publish": null,
          "archive_date": null,
          "date_last_reviewed": null,
          "content_tags": null,
          "asset_topic_taxonomy": [
              {
                  "tid": "11098",
                  "uuid": "916901b3-0032-47cf-b785-d1864c0562fa",
                  "type": "taxonomy_term",
                  "bundle": "asset_topic_taxonomy"
              }
          ],
          "related_multimedia_two": {
              "target_id": "213791",
              "uuid": "22d6ae56-3b4e-46c4-947e-fd1dccc218bc",
              "type": "node",
              "bundle": "multimedia_content_type"
          },
          "priority": "normal",
          "workflow_state_search": null,
          "blog_owner": null,
          "blog_pub_date": "1515187307",
          "usa_feature_toggle_url": null,
          "gob_feature_toggle_url": "\/novedades\/cinco-servicios-del-gobierno-de-ee-uu-que-seguro-no-conocia",
          "for_use_by": [
              "USA.gov",
              "Feature"
          ],
          "pageType": null
      },
      "22d6ae56-3b4e-46c4-947e-fd1dccc218bc": {
          "title": "Topic Application",
          "log": "Edited by julia.sultan@gsa.gov.",
          "status": "1",
          "sticky": null,
          "vuuid": "14462fe1-ef00-4424-9ba9-3e91e1f8c078",
          "nid": "213791",
          "type": "multimedia_content_type",
          "language": "English",
          "created": "1513181682",
          "changed": "1517855425",
          "tnid": null,
          "translate": null,
          "uuid": "22d6ae56-3b4e-46c4-947e-fd1dccc218bc",
          "name": "puthorn.suwannasingh@gsa.gov",
          "deleted": null,
          "alt_text": "cell phone with application. ",
          "comments": null,
          "description": "Topic applications featured image",
          "embed_code": null,
          "for_use_by": "USA.gov",
          "media_type": "Image",
          "notify_marketing_team": "No",
          "transcript": null,
          "schedule_publish": null,
          "archive_date": null,
          "date_last_reviewed": null,
          "content_tags": null,
          "asset_topic_taxonomy": [],
          "url": null,
          "high_res_version": null,
          "widget_code": null,
          "priority": "normal",
          "info_for_contact_center": null,
          "workflow_state_search": null,
          "file_media": {
              "fid": "833202bf-2957-4910-a6cd-1e4aee2fbc8e",
              "uid": "0912ea57-427e-4e72-af5e-6335a8ba177c",
              "filename": "Topic_App.jpg",
              "uri": "\/\/app_usa_prod_eqffnyamdzrb.s3.amazonaws.com\/Topic_App.jpg",
              "filemime": "image\/jpeg",
              "filesize": "100837",
              "status": "1",
              "timestamp": "1513181615",
              "type": "image",
              "uuid": "833202bf-2957-4910-a6cd-1e4aee2fbc8e",
              "field_file_image_alt_text": [],
              "field_file_image_title_text": [],
              "_drafty_revision_requested": "FIELD_LOAD_CURRENT",
              "rdf_mapping": [],
              "metadata": {
                  "height": 582,
                  "width": 600
              },
              "height": "582",
              "width": "600",
              "alt": null,
              "title": null
          },
          "pageType": null
      },
      "ee77187e-4996-46f8-9c83-2dc5418f04d1": {
          "title": "Kids and Depression",
          "log": "Edited by julia.sultan@gsa.gov.",
          "status": "1",
          "sticky": null,
          "vuuid": "dc639c44-d0e1-4a88-9f39-5556b89d86d3",
          "nid": "213823",
          "type": "text_content_type",
          "language": "English",
          "created": "1516116107",
          "changed": "1517864439",
          "tnid": null,
          "translate": null,
          "uuid": "ee77187e-4996-46f8-9c83-2dc5418f04d1",
          "body": "<p>You know in your heart something&rsquo;s not right. Your child is withdrawn and just seems so sad. It&rsquo;s hard to see them in so much pain.&nbsp;<\/p><p>One in five teens experiences depression. And depressed kids are at a greater risk for substance abuse and suicide attempts.&nbsp;&nbsp;<\/p><p>This guide from USA.gov helps you recognize and talk to your child about depression, and find the help they need to feel better again.<\/p><h3>For Parents, Grandparents, and Teachers<\/h3><ul><li><p>It&rsquo;s normal for younger children to worry or be afraid sometimes. Learn what to do if those feelings grow and&nbsp;<a href=\"https:\/\/www.cdc.gov\/childrensmentalhealth\/depression.html\">turn into anxiety or depression<\/a>.<\/p><\/li><li><p>Certain life experiences can make teens vulnerable to depression. Find out the&nbsp;<a href=\"https:\/\/medlineplus.gov\/ency\/patientinstructions\/000648.htm\">risk factors and signs of depression in teens<\/a>.<\/p><\/li><li><p>Counseling or medication can help.&nbsp;<a href=\"https:\/\/kidshealth.org\/en\/parents\/finding-therapist.html#\">Learn about treatment options, what to consider when selecting a therapist, and how to prepare for the first appointment<\/a>.<\/p><\/li><\/ul><h3>To Share with Your Child<\/h3><h4>For Younger Kids<\/h4><ul><li><p>When sadness is deep and lasts a long time, it&rsquo;s called depression.&nbsp;<a href=\"https:\/\/kidshealth.org\/en\/kids\/depression.html\">Learn what that means, and what you can do to feel better.<\/a><\/p><\/li><li><p>Talking can help.&nbsp;<a href=\"http:\/\/kidshealth.org\/en\/kids\/talk-feelings.html?WT.ac=k-ra\">Get ideas for&nbsp;sharing your feelings<\/a>&nbsp;with someone you trust and&nbsp;<a href=\"https:\/\/kidshealth.org\/en\/kids\/going-to-therapist.html?WT.ac=p-ra#\">find out what it&rsquo;s like to visit a therapist or counselor<\/a>.<\/p><\/li><\/ul><h4>For Teens and College Students<\/h4><ul><li><p><a href=\"http:\/\/kidshealth.org\/en\/teens\/depression.html?WT.ac=t-ra#\">Depression can be confused with normal sadness or a bad attitude.<\/a>&nbsp;Learn how to explain what you&rsquo;re feeling&nbsp;<a href=\"https:\/\/kidshealth.org\/en\/teens\/talk-depression.html?WT.ac=t-ra\">to your parents<\/a>&nbsp;or&nbsp;<a href=\"https:\/\/kidshealth.org\/en\/teens\/therapist.html?WT.ac=t-ra\">to a counselor or therapist<\/a>.<\/p><\/li><li><p>Severe depression can put you or a friend who&rsquo;s experiencing it in danger.&nbsp;<a href=\"http:\/\/kidshealth.org\/en\/teens\/severe-depression.html?WT.ac=t-ra\">Find out how to get urgent help.<\/a><\/p><\/li><li><p>College can be exciting, but it can become overwhelming.&nbsp;<a href=\"https:\/\/www.nimh.nih.gov\/health\/publications\/depression-and-college-students\/index.shtml\">Get answers to college students&rsquo; questions about depression<\/a>.<\/p><\/li><\/ul><h3>If You Think Your Child Might be Suicidal<\/h3><p>Contact the&nbsp;<a href=\"https:\/\/suicidepreventionlifeline.org\/\">National Suicide Prevention Lifeline<\/a>&nbsp;at 1-800-273-8255 for confidential help 24 hours a day.<\/p><p><a href=\"http:\/\/suicideprevention.nv.gov\/Youth\/WhatYouCanDo\/\">Learn ways to prevent suicide, signs to watch for, and advice for helping your child heal psychologically following a suicide attempt.<\/a><\/p>",
          "name": "nancy.tyler@gsa.gov",
          "deleted": null,
          "comments": "This is the January, 2018 Dear Abby promotion. Abby's 1\/24\/18 column will link to this feature. Please contact Nancy if you have any questions. Thanks!",
          "description": "Learn the signs and risk factors for depression in teens and younger children and find out how you can help them heal.",
          "notify_marketing_team": "No",
          "contact_center_info": null,
          "for_use_by_text": [
              "USA.gov",
              "Feature"
          ],
          "schedule_publish": null,
          "archive_date": null,
          "date_last_reviewed": {
              "value": "2018-01-16 17:00:00",
              "timezone": "America\/New_York",
              "timezone_db": "UTC",
              "date_type": "datetime"
          },
          "content_tags": null,
          "asset_topic_taxonomy": [
              {
                  "tid": "11098",
                  "uuid": "916901b3-0032-47cf-b785-d1864c0562fa",
                  "type": "taxonomy_term",
                  "bundle": "asset_topic_taxonomy"
              }
          ],
          "related_multimedia_two": {
              "target_id": "213824",
              "uuid": "e0cf90e2-1507-4a74-b6ef-f6f9c24c6796",
              "type": "node",
              "bundle": "multimedia_content_type"
          },
          "priority": "normal",
          "workflow_state_search": null,
          "blog_owner": null,
          "blog_pub_date": "1516292964",
          "usa_feature_toggle_url": null,
          "gob_feature_toggle_url": null,
          "for_use_by": [
              "USA.gov",
              "Feature"
          ],
          "pageType": null
      },
      "e0cf90e2-1507-4a74-b6ef-f6f9c24c6796": {
          "title": "Kids and Depression",
          "log": "Edited by julia.sultan@gsa.gov.",
          "status": "1",
          "sticky": null,
          "vuuid": "07c72901-5672-48d7-b1bc-13571edc3250",
          "nid": "213824",
          "type": "multimedia_content_type",
          "language": "English",
          "created": "1516135756",
          "changed": "1517854513",
          "tnid": null,
          "translate": null,
          "uuid": "e0cf90e2-1507-4a74-b6ef-f6f9c24c6796",
          "name": "edgardo.morales@gsa.gov",
          "deleted": null,
          "alt_text": "mother hugs her kid",
          "comments": null,
          "description": "Mother embracing and soothing depressed daughter in the living room. \r\n",
          "embed_code": null,
          "for_use_by": "USA.gov",
          "media_type": "Image",
          "notify_marketing_team": "No",
          "transcript": null,
          "schedule_publish": null,
          "archive_date": null,
          "date_last_reviewed": null,
          "content_tags": null,
          "asset_topic_taxonomy": [],
          "url": null,
          "high_res_version": null,
          "widget_code": null,
          "priority": "normal",
          "info_for_contact_center": null,
          "workflow_state_search": null,
          "file_media": {
              "fid": "7c6ae291-a4bc-4ebe-a251-ec7da86d90f2",
              "uid": "afc1e1c6-348b-433b-b81b-1ee5a882c4dd",
              "filename": "Kids_And_Depression.jpg",
              "uri": "\/\/app_usa_prod_eqffnyamdzrb.s3.amazonaws.com\/ThinkstockPhotos-466168847 (1).jpg",
              "filemime": "image\/jpeg",
              "filesize": "83567",
              "status": "1",
              "timestamp": "1516135941",
              "type": "image",
              "uuid": "7c6ae291-a4bc-4ebe-a251-ec7da86d90f2",
              "field_file_image_alt_text": [],
              "field_file_image_title_text": [],
              "_drafty_revision_requested": "FIELD_LOAD_CURRENT",
              "rdf_mapping": [],
              "metadata": {
                  "height": 342,
                  "width": 500
              },
              "height": "342",
              "width": "500",
              "alt": null,
              "title": null
          },
          "pageType": null
      },
      "fe91f32a-c84b-4211-a339-3e3253c713b9": {
          "title": "This Is Just a Drill",
          "log": "Edited by julia.sultan@gsa.gov.",
          "status": "1",
          "sticky": null,
          "vuuid": "868728b0-b7b1-4e66-becd-a54c995c9153",
          "nid": "213753",
          "type": "text_content_type",
          "language": "English",
          "created": "1509646280",
          "changed": "1517863553",
          "tnid": null,
          "translate": null,
          "uuid": "fe91f32a-c84b-4211-a339-3e3253c713b9",
          "body": "<p>There has been confusion and rumors on social media about a U.S. Department of Defense drill that starts on November 4, 2017. Some people are worried about problems like power or communications systems being purposefully shut down. In fact, there were more than one million searches for this topic on U.S. federal government websites during a recent 24-hour period. People looked up terms like &quot;emp,&quot; &quot;drill,&quot; and &quot;electromagnetic pulse.&quot;<\/p><p>However, the exercise will only <a href=\"https:\/\/www.army.mil\/article\/196288\/quarterly_communication_exercise_uses_simulated_scenario_to_test_interoperability_of_army_mars\">simulate<\/a> a massive power outage. The participants will be pretending that they don&#39;t have regular access to power. Power and communications for the U.S. will not be affected.<\/p><p>The radio operators in the drill will try to communicate with each other in order to test how well their different communication systems connect. The purpose of the exercise is to rehearse for a massive power outage scenario and find out what problems arise in order to address them later.<\/p><p>The exercise is being performed by the Army Military Auxiliary Radio System (MARS), which conducts these tests on a regular basis. This test was scheduled more than a year ago in order to prepare and encourage participation from volunteers, such as emergency responders and the amateur radio community. This MARS exercise involves the Army, the Department of Defense, and hundreds of trained volunteers.<\/p><p><a href=\"https:\/\/www.army.mil\/article\/196288\/quarterly_communication_exercise_uses_simulated_scenario_to_test_interoperability_of_army_mars\">Learn more about the exercise from the U.S. Army<\/a>.<\/p>",
          "name": "edgardo.morales@gsa.gov",
          "deleted": null,
          "comments": null,
          "description": "There has been confusion and rumors on social media about a U.S. Department of Defense drill that starts on November 4, 2017.",
          "notify_marketing_team": "No",
          "contact_center_info": null,
          "for_use_by_text": [
              "USA.gov",
              "Feature"
          ],
          "schedule_publish": null,
          "archive_date": null,
          "date_last_reviewed": null,
          "content_tags": null,
          "asset_topic_taxonomy": [
              {
                  "tid": "11098",
                  "uuid": "916901b3-0032-47cf-b785-d1864c0562fa",
                  "type": "taxonomy_term",
                  "bundle": "asset_topic_taxonomy"
              }
          ],
          "related_multimedia_two": {
              "target_id": "213752",
              "uuid": "aac22b1e-214f-447c-8506-5976f1515f92",
              "type": "node",
              "bundle": "multimedia_content_type"
          },
          "priority": "normal",
          "workflow_state_search": null,
          "blog_owner": null,
          "blog_pub_date": "1509646283",
          "usa_feature_toggle_url": null,
          "gob_feature_toggle_url": null,
          "for_use_by": [
              "USA.gov",
              "Feature"
          ],
          "pageType": null
      },
      "aac22b1e-214f-447c-8506-5976f1515f92": {
          "title": "This is a drill image",
          "log": "Edited by julia.sultan@gsa.gov.",
          "status": "1",
          "sticky": null,
          "vuuid": "8c631305-4ab1-41e6-84a9-d38f4aa5757d",
          "nid": "213752",
          "type": "multimedia_content_type",
          "language": "English",
          "created": "1509646227",
          "changed": "1517863375",
          "tnid": null,
          "translate": null,
          "uuid": "aac22b1e-214f-447c-8506-5976f1515f92",
          "name": "edgardo.morales@gsa.gov",
          "deleted": null,
          "alt_text": "Soldier responds on a radio device. ",
          "comments": null,
          "description": "Soldier responds on a radio device. ",
          "embed_code": null,
          "for_use_by": "USA.gov",
          "media_type": "Image",
          "notify_marketing_team": "No",
          "transcript": null,
          "schedule_publish": null,
          "archive_date": null,
          "date_last_reviewed": null,
          "content_tags": null,
          "asset_topic_taxonomy": [],
          "url": null,
          "high_res_version": null,
          "widget_code": null,
          "priority": "normal",
          "info_for_contact_center": null,
          "workflow_state_search": null,
          "file_media": {
              "fid": "d25ce87c-abda-46c0-a78c-ad7bd165aaa7",
              "uid": "afc1e1c6-348b-433b-b81b-1ee5a882c4dd",
              "filename": "drill feature.png",
              "uri": "\/\/app_usa_prod_eqffnyamdzrb.s3.amazonaws.com\/drill feature.png",
              "filemime": "image\/png",
              "filesize": "219672",
              "status": "1",
              "timestamp": "1509646217",
              "type": "image",
              "uuid": "d25ce87c-abda-46c0-a78c-ad7bd165aaa7",
              "field_file_image_alt_text": [],
              "field_file_image_title_text": [],
              "_drafty_revision_requested": "FIELD_LOAD_CURRENT",
              "rdf_mapping": [],
              "metadata": {
                  "height": 400,
                  "width": 316
              },
              "height": "400",
              "width": "316",
              "alt": null,
              "title": null
          },
          "pageType": null
      },
      "689a061b-4ca3-4621-ab5c-944e74b1fae1": {
          "title": "Navigating Power of Attorney: How to Help Loved Ones Manage Their Money",
          "log": "Edited by stephanie.madden@gsa.gov.",
          "status": "1",
          "sticky": null,
          "vuuid": "fc10ec84-0152-4fd0-8772-1852b7eeecda",
          "nid": "211842",
          "type": "text_content_type",
          "language": "English",
          "created": "1441031609",
          "changed": "1505783036",
          "tnid": null,
          "translate": null,
          "uuid": "689a061b-4ca3-4621-ab5c-944e74b1fae1",
          "body": "<p>Managing your finances can be hard. Managing the finances of a relative or a friend &nbsp;can be even harder. You want to honor your loved one&rsquo;s wishes and respect his or her boundaries, but at the same time you need to act in his or her best interest. It can be hard to know where to begin or whom to trust. Not only are there legal obligations that come with this responsibility, but the added emotional stress of caring for a family member or friend &nbsp;can feel overwhelming.<\/p><p>So let&rsquo;s start with the basics: What is a power of attorney? What does it mean for you, and what should you look out for? Being informed, prepared, and alert will help make a difficult situation as comfortable as possible for all &nbsp;involved.<\/p><h3>Be Informed: What Is a Power of Attorney?<\/h3><p>A power of attorney is a written document in which one person gives legal authority to another to make decisions about his or her money or property. If you&rsquo;ve been named to manage money or property for someone else under a power of attorney, you are the <strong>fiduciary<\/strong>. It doesn&rsquo;t matter if you&rsquo;re managing a small amount of money or a lot, or if you&rsquo;re a family member or not &ndash; you&rsquo;re now legally responsible for managing &nbsp;that money or property for the benefit of that person, known as the <strong>principal<\/strong>.<\/p><p>If you were chosen as &nbsp;fiduciary, the principal sees you as a trustworthy, honest, and responsible person. Preparing yourself with the necessary information will help you manage your responsibilities and will bring you, and everyone involved, peace of mind. &nbsp;<\/p><h3>Be Prepared: Understanding Your Legal Duties<\/h3><p>While a power of attorney can seem like a complex document, there are really just four major duties you need to execute as fiduciary. Your legal responsibilities are to:<\/p><ul><li>Act only in the principal&rsquo;s best interest.<\/li><li>Manage money and property carefully.<\/li><li>Keep your money and property separate from the principal&rsquo;s.<\/li><li>Keep good records.<\/li><\/ul><p>Because you&rsquo;re managing someone else&rsquo;s money, your responsibility is to make decisions that are best for that person. This means managing the money carefully, using good judgment and common sense, and never mixing your assets with the other person&rsquo;s. Keeping true and complete records is important; incorrect or incomplete records can get you in trouble &mdash; not just with the principal, but also with the police and with government agencies, such as a city&rsquo;s or state&rsquo;s Adult Protective Services office.<\/p><h3>Be Alert: Protecting Your Loved Ones From Fraud<\/h3><p>Financial exploitation has been called &ldquo;the crime of the 21st &nbsp;century.&rdquo; As a fiduciary, you should know the signs of financial exploitation. Recognizing what to look for will help you protect both yourself and your loved one. Be wary if:<\/p><ul><li>You or your loved one thinks that money or property is missing.<\/li><li>Your loved one shows sudden changes in spending and saving behavior.<\/li><li>Your loved one puts names on bank accounts and property that can&rsquo;t be explained.<\/li><li>Your loved one fears a relative, caregiver, or friend.<\/li><li>A relative shows controlling behavior towards you or a loved one.<\/li><\/ul><p>Even if your loved one controls only some (or none) of his or her funds, he or she can still be exploited. If he or she was exploited in the past, before you become involved, there still may be something you can do about it&mdash;you can, for example, alert banks and credit card companies or talk to an attorney about preventing future exploitation and recovering the property that was taken.<\/p><p>The truth is, we&rsquo;re all at risk. Anyone with any money could be targeted by a fraudster at some point. But you can help protect your family and friends by recognizing how fraudsters operate and by reporting suspicious scams and suspicious sales pitches.<\/p>",
          "name": "cecilia.koosau@gsa.gov",
          "deleted": null,
          "comments": "SAM: Deleted last paragraph that referred to apparently deleted USAgov kit: \"Check out the full Financial Self-Defense Kit from FinancialProtection.USA.gov to gather information and build the confidence you need to make smart decisions about your finances and those of the people you care about. The kit includes resources that will help you avoid scams, be an informed fiduciary, and plan for your financial future.\"",
          "description": "Be informed and prepared to take your legal duties when a power of attorney is granted to you.",
          "notify_marketing_team": "Yes",
          "contact_center_info": null,
          "for_use_by_text": [
              "USA.gov",
              "Feature"
          ],
          "schedule_publish": {
              "value": "2015-09-01 12:45:00",
              "timezone": "America\/New_York",
              "timezone_db": "UTC",
              "date_type": "datetime"
          },
          "archive_date": null,
          "date_last_reviewed": {
              "value": "2017-09-18 16:00:00",
              "timezone": "America\/New_York",
              "timezone_db": "UTC",
              "date_type": "datetime"
          },
          "content_tags": {
              "tid": "261",
              "uuid": "872f4f04-cb8f-4d0c-aa65-9ed93e8bb923",
              "type": "taxonomy_term",
              "bundle": "agency_tags"
          },
          "asset_topic_taxonomy": [
              {
                  "tid": "11098",
                  "uuid": "916901b3-0032-47cf-b785-d1864c0562fa",
                  "type": "taxonomy_term",
                  "bundle": "asset_topic_taxonomy"
              }
          ],
          "related_multimedia_two": null,
          "priority": "normal",
          "workflow_state_search": "draft",
          "blog_owner": null,
          "blog_pub_date": null,
          "usa_feature_toggle_url": null,
          "gob_feature_toggle_url": null,
          "for_use_by": [
              "USA.gov",
              "Feature"
          ],
          "pageType": null
      },

    }


    }

  }
