module.exports = {
	status: "prototype",
	title: "Homepage",
	name: "Homepage",
	order: 0,
	status: "wip",
	notes:
	`
	Example Page - https://www.usa.gov
	`,
	variants: [
	    {
	      "name": "default",
	      "label": "English",
	      "context": {
	      	"language": "English"
	      }
	  	},
	    {
	      "name": "Spanish",
	      "context": {
	      	"for_use_by": [
	      		"GobiernoUSA.gov"
	      	],
	      	"language": "Spanish",
	      	"usa_gov_toggle_url": "\/",
	      	"gobiernousa_gov_toggle_url": null 
	      }
		}
	],
	context: {
	    "tid": "10809",
	    "name": "Homepage",
	    "description": null,
	    "format": "filtered_html",
	    "weight": "1",
	    "changed": "1517509169",
	    "uuid": "bf966b28-bbba-4f93-8d9e-d59764846876",
	    "vocabulary_machine_name": "site_strucutre_taxonomy",
	    "path": "1",
	    "type": "homepage",
	    "deleted": null,
	    "parent_uuid": "b6ca6dce-3bab-40c8-b70b-08ff9d78a6e2",
	    "parent": "3062",
	    "children": null,
	    "govdelivery_id": null,
	    "page_intro": "USA.gov can help you start your search for government information by topic and agency.",
	    "head_html": null,
	    "end_html": null,
	    "generate_page": "yes",
	    "also_include_on_nav_page": null,
	    "asset_topic_taxonomy": null,
	    "page_title": "Official Guide to Government Information and Services",
	    "usefulness_survey": "0",
	    "browser_title": "Official Guide to Government Information and Services",
	    "meta_description": "USA.gov can help you start your search for government information by topic and agency.",
	    "friendly_url": "\/",
	    "usa_gov_toggle_url": null,
	    "gobiernousa_gov_toggle_url": "\/",
	    "type_of_page_to_generate": "generic-navigation-page",
	    "asset_inherit_carousel": "0",
	    "asset_inherit_content": "0",
	    "asset_inherit_sidebar": "0",
	    "asset_inherit_bottom": "0",
	    "asset_order_carousel": null,
	    "asset_order_content": null,
	    "asset_order_sidebar": null,
	    "asset_order_bottom": null,
	    "asset_inherit_menu": "0",
	    "asset_order_menu": null,
	    "generate_menu": "yes",
	    "css_class": "mortgage",
	    "usa_gov_50_state_category": null,
	    "directory_record_access_me": null,
	    "directory_record_url": null,
	    "home_alert_asset": {
		    "title": "Ack! It's a Zombie Apocalypse",
		    "log": "Edited by sandra.abrams@gsa.gov.",
		    "status": "1",
		    "sticky": null,
		    "vuuid": "d1cdfc70-92f7-4e3b-92cc-17b8521c7556",
		    "nid": "36837",
		    "type": "text_content_type",
		    "language": "English",
		    "created": "1420477092",
		    "changed": "1511196499",
		    "tnid": null,
		    "translate": null,
		    "uuid": "f1826be1-f7ec-4e19-a104-cd4247e95847",
		    "body": "<p>This is test content. Check back here in the case of an actual zombie apocalypse.</p>",
		    "name": null,
		    "deleted": null,
		    "comments": "#3314\r\nNov. 10, 2016 new version published after topic spike review and edits. Video explaining all four parts maybe added once contrast issue per accessibility team is resolved sa and added link Part D to our own asset and reordered the assets based on popularity of clicks. \r\ndeleted the line about Open Enrollment since it is now over. Dec. 8, 2016 sa\r\nJune9, 2017 cmp update. sa  September 1, 2017 revamp of Medicare for new structure. sa  Nov. 20, 2017 added sentence on how to file an appeal for contact center. sa ",
		    "description": "Learn more information about Medicare, how to apply, report fraud and complaints.",
		    "notify_marketing_team": "No",
		    "contact_center_info": null,
		    "for_use_by_text": [
		        "USA.gov",
		        "NCC Knowledge Base"
		    ],
		    "schedule_publish": null,
		    "archive_date": null,
		    "date_last_reviewed": {
		        "value": "2017-09-01 11:15:00",
		        "timezone": "America\/New_York",
		        "timezone_db": "UTC",
		        "date_type": "datetime"
		    },
		    "content_tags": [
		        {
		            "tid": "271",
		            "uuid": "7ef7035c-37fb-48ec-a27e-0eec34f923bc",
		            "type": "taxonomy_term",
		            "bundle": "agency_tags"
		        },
		        {
		            "tid": "341",
		            "uuid": "17b4f321-2aee-4762-a899-f1f82a1d0356",
		            "type": "taxonomy_term",
		            "bundle": "agency_tags",
		            "entity": {
		                "tid": "341",
		                "name": "SSA",
		                "description": null,
		                "format": null,
		                "weight": null,
		                "changed": "1484015391",
		                "uuid": "17b4f321-2aee-4762-a899-f1f82a1d0356",
		                "vocabulary_machine_name": "agency_tags",
		                "type": "taxonomy_term",
		                "deleted": null,
		                "parent": null,
		                "parent_uuid": null,
		                "children": [],
		                "for_use_by": null,
		                "pageType": null
		            }
		        }
		    ],
		    "asset_topic_taxonomy": {
		        "tid": "2737",
		        "uuid": "f1584649-1bb7-471b-a4c0-56963b54bbbf",
		        "type": "taxonomy_term",
		        "bundle": "asset_topic_taxonomy",
		        "entity": {
		            "tid": "2737",
		            "name": "Medicare",
		            "description": null,
		            "format": null,
		            "weight": null,
		            "changed": "1484015391",
		            "uuid": "f1584649-1bb7-471b-a4c0-56963b54bbbf",
		            "vocabulary_machine_name": "asset_topic_taxonomy",
		            "type": "taxonomy_term",
		            "deleted": null,
		            "parent_uuid": "708b0e38-3ba5-4da6-8a79-6dd0dac8229f",
		            "parent": "791",
		            "children": [],
		            "for_use_by": null,
		            "pageType": null
		        }
		    },
		    "related_multimedia_two": null,
		    "priority": "normal",
		    "workflow_state_search": "draft",
		    "blog_owner": null,
		    "blog_pub_date": null,
		    "usa_feature_toggle_url": null,
		    "gob_feature_toggle_url": null,
		    "for_use_by": [
		        "USA.gov",
		        "NCC Knowledge Base"
		    ],
		    "pageType": null
		},
	    "show_social_media_icon": null,
	    "term_owner": null,
	    "help_desk": {
	        "tid": "11443",
	        "uuid": "4504fd76-e6f0-4b6b-9cfc-dc6601d1f5ec",
	        "type": "taxonomy_term",
	        "bundle": "topic_desk_assignment"
	    },
	    "usa_gov_50_state_prefix": null,
	    "home_howdoi_assets": [
	        {
	            "title": "How Do I",
	            "log": "Edited by sandra.abrams@gsa.gov.",
	            "status": "1",
	            "sticky": null,
	            "vuuid": "d1cdfc70-92f7-4e3b-92cc-17b8521c7556",
	            "nid": "36837",
	            "type": "text_content_type",
	            "language": "English",
	            "created": "1420477092",
	            "changed": "1511196499",
	            "tnid": null,
	            "translate": null,
	            "uuid": "f1826be1-f7ec-4e19-a104-cd4247e95847",
	            "body": "<ul><li><a href=\"/unclaimed-money\">Find unclaimed money the government owes me</a></li><li><a href=\"https://www.usa.gov/forms/a\">Find government forms</a></li><li><a href=\"https://www.usa.gov/government-jobs\">Find a government job</a></li><li><a href=\"/passport\">Get or renew a passport</a></li><li><a href=\"https://www.usa.gov/benefits-grants-loans\">Find benefits, grants and loans</a></li></ul><p><a href=\"/topics\">Find All Topics and Services</a></p>",
	            "name": null,
	            "deleted": null,
	            "comments": "#3314\r\nNov. 10, 2016 new version published after topic spike review and edits.",
	            "description": "How Do I Section of Homepage",
	            "notify_marketing_team": "No",
	            "contact_center_info": null,
	            "for_use_by_text": [
	                "USA.gov",
	                "NCC Knowledge Base"
	            ],
	            "schedule_publish": null,
	            "archive_date": null,
	            "date_last_reviewed": {
	                "value": "2017-09-01 11:15:00",
	                "timezone": "America\/New_York",
	                "timezone_db": "UTC",
	                "date_type": "datetime"
	            },
	            "content_tags": null,
	            "asset_topic_taxonomy": null,
	            "related_multimedia_two": null,
	            "priority": "normal",
	            "workflow_state_search": "draft",
	            "blog_owner": null,
	            "blog_pub_date": null,
	            "usa_feature_toggle_url": null,
	            "gob_feature_toggle_url": null,
	            "for_use_by": [
	                "USA.gov",
	                "NCC Knowledge Base"
	            ],
	            "pageType": null
	        },
	        {
	            "title": "About USA Gov",
	            "log": "Edited by sandra.abrams@gsa.gov.",
	            "status": "1",
	            "sticky": null,
	            "vuuid": "d1cdfc70-92f7-4e3b-92cc-17b8521c7556",
	            "nid": "36837",
	            "type": "text_content_type",
	            "language": "English",
	            "created": "1420477092",
	            "changed": "1511196499",
	            "tnid": null,
	            "translate": null,
	            "uuid": "f1826be1-f7ec-4e19-a104-cd4247e95847",
	            "body": "<p>USA.gov is your online guide to government information and services.</p><p><a href=\"/how-to-use\">Learn what you can do on this site</a></p>",
	            "name": null,
	            "deleted": null,
	            "comments": "#3314\r\nNov. 10, 2016 new version published after topic spike review and edits.",
	            "description": "About USA Gov section of Homepage.",
	            "notify_marketing_team": "No",
	            "contact_center_info": null,
	            "for_use_by_text": [
	                "USA.gov",
	                "NCC Knowledge Base"
	            ],
	            "schedule_publish": null,
	            "archive_date": null,
	            "date_last_reviewed": {
	                "value": "2017-09-01 11:15:00",
	                "timezone": "America\/New_York",
	                "timezone_db": "UTC",
	                "date_type": "datetime"
	            },
	            "content_tags": null,
	            "asset_topic_taxonomy": null,
	            "related_multimedia_two": null,
	            "priority": "normal",
	            "workflow_state_search": "draft",
	            "blog_owner": null,
	            "blog_pub_date": null,
	            "usa_feature_toggle_url": null,
	            "gob_feature_toggle_url": null,
	            "for_use_by": [
	                "USA.gov",
	                "NCC Knowledge Base"
	            ],
	            "pageType": null
	        }
	    ],
	    "home_whats_new_asset": [
	        {
	            "title": "A Healthy Prescription For a Healthy Home",
	            "log": "Edited by sandra.abrams@gsa.gov.",
	            "status": "1",
	            "sticky": null,
	            "vuuid": "d1cdfc70-92f7-4e3b-92cc-17b8521c7556",
	            "nid": "36837",
	            "type": "text_content_type",
	            "friendly_url": "features/a-healthy-prescription-for-a-healthy-home",
	            "language": "English",
	            "created": "1420477092",
	            "changed": "1511196499",
	            "tnid": null,
	            "translate": null,
	            "uuid": "f1826be1-f7ec-4e19-a104-cd4247e95847",
	            "body": "TODO",
	            "name": null,
	            "deleted": null,
	            "comments": "#3314\r\nNov. 10, 2016 new version published after topic spike review and edits. Video explaining all four parts maybe added once contrast issue per accessibility team is resolved sa and added link Part D to our own asset and reordered the assets based on popularity of clicks. \r\ndeleted the line about Open Enrollment since it is now over. Dec. 8, 2016 sa\r\nJune9, 2017 cmp update. sa  September 1, 2017 revamp of Medicare for new structure. sa  Nov. 20, 2017 added sentence on how to file an appeal for contact center. sa ",
	            "description": "Feeling ill? Some health issues could be connected to the health of your home. Learn how to give your home a checkup. ",
	            "notify_marketing_team": "No",
	            "contact_center_info": null,
	            "for_use_by_text": [
	                "USA.gov",
	                "NCC Knowledge Base"
	            ],
	            "schedule_publish": null,
	            "archive_date": null,
	            "date_last_reviewed": {
	                "value": "2017-09-01 11:15:00",
	                "timezone": "America\/New_York",
	                "timezone_db": "UTC",
	                "date_type": "datetime"
	            },
	            "content_tags": [
	                {
	                    "tid": "271",
	                    "uuid": "7ef7035c-37fb-48ec-a27e-0eec34f923bc",
	                    "type": "taxonomy_term",
	                    "bundle": "agency_tags"
	                },
	                {
	                    "tid": "341",
	                    "uuid": "17b4f321-2aee-4762-a899-f1f82a1d0356",
	                    "type": "taxonomy_term",
	                    "bundle": "agency_tags",
	                    "entity": {
	                        "tid": "341",
	                        "name": "SSA",
	                        "description": null,
	                        "format": null,
	                        "weight": null,
	                        "changed": "1484015391",
	                        "uuid": "17b4f321-2aee-4762-a899-f1f82a1d0356",
	                        "vocabulary_machine_name": "agency_tags",
	                        "type": "taxonomy_term",
	                        "deleted": null,
	                        "parent": null,
	                        "parent_uuid": null,
	                        "children": [],
	                        "for_use_by": null,
	                        "pageType": null
	                    }
	                }
	            ],
	            "asset_topic_taxonomy": {
	                "tid": "2737",
	                "uuid": "f1584649-1bb7-471b-a4c0-56963b54bbbf",
	                "type": "taxonomy_term",
	                "bundle": "asset_topic_taxonomy",
	                "entity": {
	                    "tid": "2737",
	                    "name": "Medicare",
	                    "description": null,
	                    "format": null,
	                    "weight": null,
	                    "changed": "1484015391",
	                    "uuid": "f1584649-1bb7-471b-a4c0-56963b54bbbf",
	                    "vocabulary_machine_name": "asset_topic_taxonomy",
	                    "type": "taxonomy_term",
	                    "deleted": null,
	                    "parent_uuid": "708b0e38-3ba5-4da6-8a79-6dd0dac8229f",
	                    "parent": "791",
	                    "children": [],
	                    "for_use_by": null,
	                    "pageType": null
	                }
	            },
	            "related_multimedia_two": {
	                "title": "Ask Marietta",
	                "log": "Edited by edgardo.morales@gsa.gov.",
	                "status": "1",
	                "sticky": null,
	                "vuuid": "e700c6d4-79db-4604-8e60-9cd6d1ffc3e4",
	                "nid": "213761",
	                "type": "multimedia_content_type",
	                "language": "English",
	                "created": "1510775029",
	                "changed": "1510782834",
	                "tnid": null,
	                "translate": null,
	                "uuid": "f4b6c07e-f639-4b26-9f3c-84233ae4cb7a",
	                "name": "puthorn.suwannasingh@gsa.gov",
	                "deleted": null,
	                "alt_text": null,
	                "comments": null,
	                "description": "Ask Marietta feature image for usa.gov homepage",
	                "embed_code": null,
	                "for_use_by": "USA.gov",
	                "media_type": "Image",
	                "notify_marketing_team": "No",
	                "transcript": null,
	                "schedule_publish": null,
	                "archive_date": null,
	                "date_last_reviewed": null,
	                "content_tags": null,
	                "asset_topic_taxonomy": [],
	                "url": null,
	                "high_res_version": null,
	                "widget_code": null,
	                "priority": "normal",
	                "info_for_contact_center": null,
	                "workflow_state_search": null,
	                "file_media": {
	                    "fid": "b43b0468-4d21-4ddb-9ab4-358c138965dd",
	                    "uid": "0912ea57-427e-4e72-af5e-6335a8ba177c",
	                    "filename": "Topic_Ask_Marietta.jpg",
	                    "uri": "\/\/app_usa_prod_eqffnyamdzrb.s3.amazonaws.com\/Healthy Homes Eng.jpg",
	                    "filemime": "image\/jpeg",
	                    "filesize": "88041",
	                    "status": "1",
	                    "timestamp": "1510775017",
	                    "type": "image",
	                    "uuid": "b43b0468-4d21-4ddb-9ab4-358c138965dd",
	                    "field_file_image_alt_text": [],
	                    "field_file_image_title_text": [],
	                    "_drafty_revision_requested": "FIELD_LOAD_CURRENT",
	                    "rdf_mapping": [],
	                    "metadata": {
	                        "height": 582,
	                        "width": 600
	                    },
	                    "alt": null,
	                    "title": null,
	                    "height": "582",
	                    "width": "600"
	                },
	                "pageType": null
	            },
	            "priority": "normal",
	            "workflow_state_search": "draft",
	            "blog_owner": null,
	            "blog_pub_date": null,
	            "usa_feature_toggle_url": null,
	            "gob_feature_toggle_url": null,
	            "for_use_by": [
	                "USA.gov",
	                "NCC Knowledge Base"
	            ],
	            "pageType": null
	        },
	        {
	            "title": "Protect Yourself and Your Money Every Day",
	            "log": "Edited by sandra.abrams@gsa.gov.",
	            "status": "1",
	            "sticky": null,
	            "vuuid": "d1cdfc70-92f7-4e3b-92cc-17b8521c7556",
	            "nid": "36837",
	            "type": "text_content_type",
	            "friendly_url": "features/protect-yourself-and-your-money-every-day",
	            "language": "English",
	            "created": "1420477092",
	            "changed": "1511196499",
	            "tnid": null,
	            "translate": null,
	            "uuid": "f1826be1-f7ec-4e19-a104-cd4247e95847",
	            "body": "TODO",
	            "name": null,
	            "deleted": null,
	            "comments": "#3314\r\nNov. 10, 2016 new version published after topic spike review and edits. Video explaining all four parts maybe added once contrast issue per accessibility team is resolved sa and added link Part D to our own asset and reordered the assets based on popularity of clicks. \r\ndeleted the line about Open Enrollment since it is now over. Dec. 8, 2016 sa\r\nJune9, 2017 cmp update. sa  September 1, 2017 revamp of Medicare for new structure. sa  Nov. 20, 2017 added sentence on how to file an appeal for contact center. sa ",
	            "description": "Stay safe and informed, know what to do when a purchase or service goes wrong, and how to address it by visiting USA.gov.",
	            "notify_marketing_team": "No",
	            "contact_center_info": null,
	            "for_use_by_text": [
	                "USA.gov",
	                "NCC Knowledge Base"
	            ],
	            "schedule_publish": null,
	            "archive_date": null,
	            "date_last_reviewed": {
	                "value": "2017-09-01 11:15:00",
	                "timezone": "America\/New_York",
	                "timezone_db": "UTC",
	                "date_type": "datetime"
	            },
	            "content_tags": [
	                {
	                    "tid": "271",
	                    "uuid": "7ef7035c-37fb-48ec-a27e-0eec34f923bc",
	                    "type": "taxonomy_term",
	                    "bundle": "agency_tags"
	                },
	                {
	                    "tid": "341",
	                    "uuid": "17b4f321-2aee-4762-a899-f1f82a1d0356",
	                    "type": "taxonomy_term",
	                    "bundle": "agency_tags",
	                    "entity": {
	                        "tid": "341",
	                        "name": "SSA",
	                        "description": null,
	                        "format": null,
	                        "weight": null,
	                        "changed": "1484015391",
	                        "uuid": "17b4f321-2aee-4762-a899-f1f82a1d0356",
	                        "vocabulary_machine_name": "agency_tags",
	                        "type": "taxonomy_term",
	                        "deleted": null,
	                        "parent": null,
	                        "parent_uuid": null,
	                        "children": [],
	                        "for_use_by": null,
	                        "pageType": null
	                    }
	                }
	            ],
	            "asset_topic_taxonomy": {
	                "tid": "2737",
	                "uuid": "f1584649-1bb7-471b-a4c0-56963b54bbbf",
	                "type": "taxonomy_term",
	                "bundle": "asset_topic_taxonomy",
	                "entity": {
	                    "tid": "2737",
	                    "name": "Medicare",
	                    "description": null,
	                    "format": null,
	                    "weight": null,
	                    "changed": "1484015391",
	                    "uuid": "f1584649-1bb7-471b-a4c0-56963b54bbbf",
	                    "vocabulary_machine_name": "asset_topic_taxonomy",
	                    "type": "taxonomy_term",
	                    "deleted": null,
	                    "parent_uuid": "708b0e38-3ba5-4da6-8a79-6dd0dac8229f",
	                    "parent": "791",
	                    "children": [],
	                    "for_use_by": null,
	                    "pageType": null
	                }
	            },
	            "related_multimedia_two": {
	                "title": "Ask Marietta",
	                "log": "Edited by edgardo.morales@gsa.gov.",
	                "status": "1",
	                "sticky": null,
	                "vuuid": "e700c6d4-79db-4604-8e60-9cd6d1ffc3e4",
	                "nid": "213761",
	                "type": "multimedia_content_type",
	                "language": "English",
	                "created": "1510775029",
	                "changed": "1510782834",
	                "tnid": null,
	                "translate": null,
	                "uuid": "f4b6c07e-f639-4b26-9f3c-84233ae4cb7a",
	                "name": "puthorn.suwannasingh@gsa.gov",
	                "deleted": null,
	                "alt_text": null,
	                "comments": null,
	                "description": "Ask Marietta feature image for usa.gov homepage",
	                "embed_code": null,
	                "for_use_by": "USA.gov",
	                "media_type": "Image",
	                "notify_marketing_team": "No",
	                "transcript": null,
	                "schedule_publish": null,
	                "archive_date": null,
	                "date_last_reviewed": null,
	                "content_tags": null,
	                "asset_topic_taxonomy": [],
	                "url": null,
	                "high_res_version": null,
	                "widget_code": null,
	                "priority": "normal",
	                "info_for_contact_center": null,
	                "workflow_state_search": null,
	                "file_media": {
	                    "fid": "b43b0468-4d21-4ddb-9ab4-358c138965dd",
	                    "uid": "0912ea57-427e-4e72-af5e-6335a8ba177c",
	                    "filename": "Topic_Ask_Marietta.jpg",
	                    "uri": "\/\/app_usa_prod_eqffnyamdzrb.s3.amazonaws.com\/Front cover to make jpeg_1.jpg",
	                    "filemime": "image\/jpeg",
	                    "filesize": "88041",
	                    "status": "1",
	                    "timestamp": "1510775017",
	                    "type": "image",
	                    "uuid": "b43b0468-4d21-4ddb-9ab4-358c138965dd",
	                    "field_file_image_alt_text": [],
	                    "field_file_image_title_text": [],
	                    "_drafty_revision_requested": "FIELD_LOAD_CURRENT",
	                    "rdf_mapping": [],
	                    "metadata": {
	                        "height": 582,
	                        "width": 600
	                    },
	                    "alt": null,
	                    "title": null,
	                    "height": "582",
	                    "width": "600"
	                },
	                "pageType": null
	            },
	            "priority": "normal",
	            "workflow_state_search": "draft",
	            "blog_owner": null,
	            "blog_pub_date": null,
	            "usa_feature_toggle_url": null,
	            "gob_feature_toggle_url": null,
	            "for_use_by": [
	                "USA.gov",
	                "NCC Knowledge Base"
	            ],
	            "pageType": null
	        }
	    ],
	    "government_branch": null,
	    "for_use_by": "USA.gov",
	    "pageType": "Homepage"
	}
}
